### ISSUE TITLE
Kleiner Tippfehler 

### ISSUE THREAD

**Issue by PazzoMF** [derJunker/LineareAlgebra2Skript#6]
Zeile 1087:
st $U\subseteq V$ f-invariant, so gilt $p_{f|_k} | p_f$

anstatt $p_{f|_k}$ ist es $p_{f|_U}$

Video vom 17.05.2021
ca. 14:50-15:00 min

selber Tippfehler in Zeile 1093 und 1098
"Würde nur stimmen, wenn Unterraum als K definiert worden wäre ist aber als U definiert"

Großartige Arbeit! 
Viele Grüße

**Comment by derJunker** [comment]
Danke, wird behoben👌🏼Vg Jonas Heitz
-------- Ursprüngliche Nachricht --------Von: PazzoMF ***@***.***> Datum: 25.05.21  08:44  (GMT+01:00) An: derJunker/LineareAlgebra2Skript ***@***.***> Cc: Subscribed ***@***.***> Betreff: [derJunker/LineareAlgebra2Skript] Kleiner Tippfehler  (#6) 

Zeile 1087:

st $U\subseteq V$ f-invariant, so gilt $p_{f|_k} | p_f$

anstatt $p_{f|k}$ ist es $p{f|_U}$

Video vom 17.05.2021

ca. 14:50-15:00 min

Viele Grüße
